/*
 ==============================================================================
 
 This file was auto-generated by the Introjucer!
 
 It contains the basic framework code for a JUCE plugin editor.
 
 ==============================================================================
 */

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"


//==============================================================================
/**
 */
class FooHarmonizerAudioProcessorEditor: public AudioProcessorEditor, private Slider::Listener, public Button::Listener
{
public:
    FooHarmonizerAudioProcessorEditor (FooHarmonizerAudioProcessor&);
    ~FooHarmonizerAudioProcessorEditor();
    
    //==============================================================================
    void paint (Graphics&) override;
    void resized() override;
    // Slider Listener (dynamic interaction)
    void sliderValueChanged(Slider* slider);
    // Button Listeners
    void buttonClicked (Button* button);
    void buttonStateChanged (Button* button);
    
private:
    // This reference is provided as a quick way for your editor to
    // access the processor object that created it.
    FooHarmonizerAudioProcessor& processor;
    
    // Create Slider function
    void createSlider(Slider &slider, Slider::SliderStyle style, double defaultVal,
                      double min, double max, double incr, std::string name);
    // Create Label function
    void createLabel(Label &label, std::string name);
    
    // Slider variables
    Slider mixSlider;
    Slider pitchSlider;
    Slider lowpassSlider;
    Slider highpassSlider;
    
    // Text Label variables
    Label mixText;
    Label pitchText;
    Label lowpassText;
    Label highpassText;
    
    // Button variables
    TextButton filterButton;
    TextButton orderButton;
    
    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (FooHarmonizerAudioProcessorEditor)
};


#endif  // PLUGINEDITOR_H_INCLUDED
